#%RAML 0.8
---
title: Mobile Banking API
version: v0.1
baseUri: http://whishworks-poc/api/

/WeatherMap:
 get:
    description: Get the Details of Country based on Cities
    queryParameters:
           Account_No: 
             displayName: CountryName
             description: Provide CountryName to get list of Cities from Countires
             required: true
             type: String
             example: India
    responses:
      200:
        body:
          application/xml:
            example: !include whetherMap_details_example.xml
